#!/bin/bash
# Istota container entrypoint.
# Waits for Nextcloud provisioning, completes API-based setup, starts scheduler.

set -euo pipefail

CONFIG_FILE="/data/config/config.toml"
PROVISION_FLAG="/mnt/shared/.istota-provisioned"
API_PROVISION_FLAG="/data/config/.api-provisioned"
NC_URL="${NC_INTERNAL_URL:-http://nextcloud}"

# --- Wait for Nextcloud provisioning (occ-based, runs in NC container) ---

echo "[istota] Waiting for Nextcloud provisioning..."
WAIT=0
while [ ! -f "$PROVISION_FLAG" ]; do
    sleep 5
    WAIT=$((WAIT + 5))
    if [ "$WAIT" -ge 600 ]; then
        echo "[istota] ERROR: Timed out waiting for provisioning after 600s"
        exit 1
    fi
    if [ $((WAIT % 30)) -eq 0 ]; then
        echo "[istota] Still waiting for provisioning... (${WAIT}s)"
    fi
done

echo "[istota] Provisioning detected."

# shellcheck source=/dev/null
source "$PROVISION_FLAG"

# --- API-based provisioning (Talk room, uses NC HTTP API) ---

APP_PASSWORD="${BOT_PASSWORD}"
ROOM_TOKEN=""

if [ ! -f "$API_PROVISION_FLAG" ]; then
    echo "[istota] Running API-based provisioning..."

    # Wait for Nextcloud API to be responsive
    echo "[istota] Waiting for Nextcloud API..."
    for i in $(seq 1 30); do
        if curl -sf "${NC_URL}/status.php" | grep -q '"installed":true'; then
            echo "[istota] Nextcloud API ready."
            break
        fi
        sleep 2
    done

    # Create Talk 1:1 room
    ROOM_TOKEN=$(curl -sf \
        -u "${BOT_USER:-istota}:${BOT_PASSWORD}" \
        -H "OCS-APIRequest: true" \
        -H "Content-Type: application/json" \
        -X POST "${NC_URL}/ocs/v2.php/apps/spreed/api/v4/room?format=json" \
        -d "{\"roomType\":1,\"invite\":\"${USER_NAME}\"}" \
        | python3 -c "import sys,json; print(json.loads(sys.stdin.read())['ocs']['data']['token'])" 2>/dev/null || echo "")

    if [ -n "$ROOM_TOKEN" ]; then
        echo "[istota] Talk room created: ${ROOM_TOKEN}"
    else
        echo "[istota] Warning: could not create Talk room. Create one manually in Nextcloud Talk."
    fi

    # Save API provisioning results
    cat > "$API_PROVISION_FLAG" <<EOF
APP_PASSWORD=${APP_PASSWORD}
ROOM_TOKEN=${ROOM_TOKEN}
EOF

    echo "[istota] API provisioning complete."
else
    echo "[istota] API provisioning already done, reading results..."
    # shellcheck source=/dev/null
    source "$API_PROVISION_FLAG"
fi

# --- Generate config ---

if [ ! -f "$CONFIG_FILE" ]; then
    echo "[istota] Generating config.toml..."

    DISPLAY_NAME="${USER_DISPLAY_NAME:-$USER_NAME}"
    TIMEZONE="${USER_TIMEZONE:-UTC}"

    cat > "$CONFIG_FILE" <<TOML
# Istota configuration — generated by Docker entrypoint

bot_name = "${ISTOTA_BOT_NAME:-Istota}"
emissaries_enabled = ${ISTOTA_EMISSARIES_ENABLED:-true}

db_path = "/data/db/istota.db"
nextcloud_mount_path = "/mnt/shared"
skills_dir = "/app/config/skills"
temp_dir = "/data/tmp"
max_memory_chars = ${ISTOTA_MAX_MEMORY_CHARS:-0}
TOML

    # Model (optional)
    if [ -n "${ISTOTA_MODEL:-}" ]; then
        echo "model = \"${ISTOTA_MODEL}\"" >> "$CONFIG_FILE"
    fi

    # Disabled skills (optional)
    if [ -n "${ISTOTA_DISABLED_SKILLS:-}" ]; then
        echo "disabled_skills = [$(echo "$ISTOTA_DISABLED_SKILLS" | sed 's/[^,]*/"&"/g')]" >> "$CONFIG_FILE"
    fi

    cat >> "$CONFIG_FILE" <<TOML

[security]
sandbox_enabled = ${ISTOTA_SECURITY_SANDBOX_ENABLED:-true}
skill_proxy_enabled = ${ISTOTA_SECURITY_SKILL_PROXY_ENABLED:-true}
skill_proxy_timeout = ${ISTOTA_SECURITY_SKILL_PROXY_TIMEOUT:-300}

[security.network]
enabled = false

[nextcloud]
url = "${NC_URL}"
username = "${BOT_USER:-istota}"
app_password = "${APP_PASSWORD}"

[talk]
enabled = ${ISTOTA_TALK_ENABLED:-true}
bot_username = "${BOT_USER:-istota}"

[email]
enabled = ${ISTOTA_EMAIL_ENABLED:-false}
TOML

    if [ "${ISTOTA_EMAIL_ENABLED:-false}" = "true" ]; then
        cat >> "$CONFIG_FILE" <<TOML
imap_host = "${ISTOTA_EMAIL_IMAP_HOST:-}"
imap_port = ${ISTOTA_EMAIL_IMAP_PORT:-993}
imap_user = "${ISTOTA_EMAIL_IMAP_USER:-}"
imap_password = "${ISTOTA_EMAIL_IMAP_PASSWORD:-}"
smtp_host = "${ISTOTA_EMAIL_SMTP_HOST:-}"
smtp_port = ${ISTOTA_EMAIL_SMTP_PORT:-587}
poll_folder = "${ISTOTA_EMAIL_POLL_FOLDER:-INBOX}"
bot_email = "${ISTOTA_EMAIL_BOT_ADDRESS:-}"
TOML
    fi

    cat >> "$CONFIG_FILE" <<TOML

[conversation]
enabled = ${ISTOTA_CONVERSATION_ENABLED:-true}
lookback_count = ${ISTOTA_CONVERSATION_LOOKBACK_COUNT:-25}
selection_model = "${ISTOTA_CONVERSATION_SELECTION_MODEL:-haiku}"
selection_timeout = ${ISTOTA_CONVERSATION_SELECTION_TIMEOUT:-30.0}
skip_selection_threshold = ${ISTOTA_CONVERSATION_SKIP_SELECTION_THRESHOLD:-3}
use_selection = ${ISTOTA_CONVERSATION_USE_SELECTION:-true}
always_include_recent = ${ISTOTA_CONVERSATION_ALWAYS_INCLUDE_RECENT:-5}
context_truncation = ${ISTOTA_CONVERSATION_CONTEXT_TRUNCATION:-0}
context_recency_hours = ${ISTOTA_CONVERSATION_CONTEXT_RECENCY_HOURS:-0}
context_min_messages = ${ISTOTA_CONVERSATION_CONTEXT_MIN_MESSAGES:-10}
previous_tasks_count = ${ISTOTA_CONVERSATION_PREVIOUS_TASKS_COUNT:-3}
talk_context_limit = ${ISTOTA_CONVERSATION_TALK_CONTEXT_LIMIT:-100}

[logging]
level = "${ISTOTA_LOGGING_LEVEL:-INFO}"
output = "${ISTOTA_LOGGING_OUTPUT:-console}"
file = "${ISTOTA_LOGGING_FILE:-}"
rotate = ${ISTOTA_LOGGING_ROTATE:-true}
max_size_mb = ${ISTOTA_LOGGING_MAX_SIZE_MB:-10}
backup_count = ${ISTOTA_LOGGING_BACKUP_COUNT:-5}

[scheduler]
poll_interval = ${ISTOTA_SCHEDULER_POLL_INTERVAL:-5}
talk_poll_interval = ${ISTOTA_SCHEDULER_TALK_POLL_INTERVAL:-10}
talk_poll_timeout = ${ISTOTA_SCHEDULER_TALK_POLL_TIMEOUT:-30}
talk_poll_wait = ${ISTOTA_SCHEDULER_TALK_POLL_WAIT:-2.0}
email_poll_interval = ${ISTOTA_SCHEDULER_EMAIL_POLL_INTERVAL:-60}
briefing_check_interval = ${ISTOTA_SCHEDULER_BRIEFING_CHECK_INTERVAL:-60}
tasks_file_poll_interval = ${ISTOTA_SCHEDULER_TASKS_FILE_POLL_INTERVAL:-30}
shared_file_check_interval = ${ISTOTA_SCHEDULER_SHARED_FILE_CHECK_INTERVAL:-120}
heartbeat_check_interval = ${ISTOTA_SCHEDULER_HEARTBEAT_CHECK_INTERVAL:-60}
progress_updates = ${ISTOTA_SCHEDULER_PROGRESS_UPDATES:-true}
progress_min_interval = ${ISTOTA_SCHEDULER_PROGRESS_MIN_INTERVAL:-8}
progress_max_messages = ${ISTOTA_SCHEDULER_PROGRESS_MAX_MESSAGES:-5}
progress_show_tool_use = ${ISTOTA_SCHEDULER_PROGRESS_SHOW_TOOL_USE:-true}
progress_show_text = ${ISTOTA_SCHEDULER_PROGRESS_SHOW_TEXT:-false}
progress_text_max_chars = ${ISTOTA_SCHEDULER_PROGRESS_TEXT_MAX_CHARS:-200}
progress_style = "${ISTOTA_SCHEDULER_PROGRESS_STYLE:-replace}"
progress_max_display_items = ${ISTOTA_SCHEDULER_PROGRESS_MAX_DISPLAY_ITEMS:-20}
task_timeout_minutes = ${ISTOTA_SCHEDULER_TASK_TIMEOUT_MINUTES:-30}
confirmation_timeout_minutes = ${ISTOTA_SCHEDULER_CONFIRMATION_TIMEOUT_MINUTES:-120}
stale_pending_warn_minutes = ${ISTOTA_SCHEDULER_STALE_PENDING_WARN_MINUTES:-30}
stale_pending_fail_hours = ${ISTOTA_SCHEDULER_STALE_PENDING_FAIL_HOURS:-2}
max_retry_age_minutes = ${ISTOTA_SCHEDULER_MAX_RETRY_AGE_MINUTES:-60}
task_retention_days = ${ISTOTA_SCHEDULER_TASK_RETENTION_DAYS:-7}
email_retention_days = ${ISTOTA_SCHEDULER_EMAIL_RETENTION_DAYS:-7}
worker_idle_timeout = ${ISTOTA_SCHEDULER_WORKER_IDLE_TIMEOUT:-30}
max_foreground_workers = ${ISTOTA_SCHEDULER_MAX_FOREGROUND_WORKERS:-3}
max_background_workers = ${ISTOTA_SCHEDULER_MAX_BACKGROUND_WORKERS:-2}
user_max_foreground_workers = ${ISTOTA_SCHEDULER_USER_MAX_FOREGROUND_WORKERS:-2}
user_max_background_workers = ${ISTOTA_SCHEDULER_USER_MAX_BACKGROUND_WORKERS:-1}
scheduled_job_max_consecutive_failures = ${ISTOTA_SCHEDULER_SCHEDULED_JOB_MAX_CONSECUTIVE_FAILURES:-5}
feed_page_regen_interval = ${ISTOTA_SCHEDULER_FEED_PAGE_REGEN_INTERVAL:-300}
talk_cache_max_per_conversation = ${ISTOTA_SCHEDULER_TALK_CACHE_MAX_PER_CONVERSATION:-200}
temp_file_retention_days = ${ISTOTA_SCHEDULER_TEMP_FILE_RETENTION_DAYS:-7}
location_ping_retention_days = ${ISTOTA_SCHEDULER_LOCATION_PING_RETENTION_DAYS:-365}

[sleep_cycle]
enabled = ${ISTOTA_SLEEP_CYCLE_ENABLED:-true}
cron = "${ISTOTA_SLEEP_CYCLE_CRON:-0 2 * * *}"
lookback_hours = ${ISTOTA_SLEEP_CYCLE_LOOKBACK_HOURS:-24}
memory_retention_days = ${ISTOTA_SLEEP_CYCLE_MEMORY_RETENTION_DAYS:-0}
auto_load_dated_days = ${ISTOTA_SLEEP_CYCLE_AUTO_LOAD_DATED_DAYS:-3}
curate_user_memory = ${ISTOTA_SLEEP_CYCLE_CURATE_USER_MEMORY:-false}

[channel_sleep_cycle]
enabled = ${ISTOTA_CHANNEL_SLEEP_CYCLE_ENABLED:-true}
cron = "${ISTOTA_CHANNEL_SLEEP_CYCLE_CRON:-0 3 * * *}"
lookback_hours = ${ISTOTA_CHANNEL_SLEEP_CYCLE_LOOKBACK_HOURS:-24}
memory_retention_days = ${ISTOTA_CHANNEL_SLEEP_CYCLE_MEMORY_RETENTION_DAYS:-0}

[memory_search]
enabled = ${ISTOTA_MEMORY_SEARCH_ENABLED:-false}
TOML

    if [ "${ISTOTA_MEMORY_SEARCH_ENABLED:-false}" = "true" ]; then
        cat >> "$CONFIG_FILE" <<TOML
auto_index_conversations = ${ISTOTA_MEMORY_SEARCH_AUTO_INDEX_CONVERSATIONS:-true}
auto_index_memory_files = ${ISTOTA_MEMORY_SEARCH_AUTO_INDEX_MEMORY_FILES:-true}
auto_recall = ${ISTOTA_MEMORY_SEARCH_AUTO_RECALL:-false}
auto_recall_limit = ${ISTOTA_MEMORY_SEARCH_AUTO_RECALL_LIMIT:-5}
TOML
    fi

    # ntfy notifications (optional)
    if [ "${ISTOTA_NTFY_ENABLED:-false}" = "true" ]; then
        cat >> "$CONFIG_FILE" <<TOML

[ntfy]
enabled = true
server_url = "${ISTOTA_NTFY_SERVER_URL:-https://ntfy.sh}"
topic = "${ISTOTA_NTFY_TOPIC:-}"
priority = ${ISTOTA_NTFY_PRIORITY:-3}
TOML
        if [ -n "${ISTOTA_NTFY_TOKEN:-}" ]; then
            echo "token = \"${ISTOTA_NTFY_TOKEN}\"" >> "$CONFIG_FILE"
        fi
        if [ -n "${ISTOTA_NTFY_USERNAME:-}" ]; then
            echo "username = \"${ISTOTA_NTFY_USERNAME}\"" >> "$CONFIG_FILE"
            echo "password = \"${ISTOTA_NTFY_PASSWORD:-}\"" >> "$CONFIG_FILE"
        fi
    fi

    # Browser (optional)
    if [ "${ISTOTA_BROWSER_ENABLED:-false}" = "true" ]; then
        cat >> "$CONFIG_FILE" <<TOML

[browser]
enabled = true
api_url = "${ISTOTA_BROWSER_API_URL:-http://localhost:9223}"
vnc_url = "${ISTOTA_BROWSER_VNC_URL:-}"
TOML
    fi

    # Location tracking (optional)
    if [ "${ISTOTA_LOCATION_ENABLED:-false}" = "true" ]; then
        cat >> "$CONFIG_FILE" <<TOML

[location]
enabled = true
webhooks_port = ${ISTOTA_WEBHOOKS_PORT:-8765}
TOML
    fi

    # Developer skill (optional)
    if [ "${ISTOTA_DEVELOPER_ENABLED:-false}" = "true" ]; then
        cat >> "$CONFIG_FILE" <<TOML

[developer]
enabled = true
repos_dir = "${ISTOTA_DEVELOPER_REPOS_DIR:-}"
gitlab_url = "${ISTOTA_DEVELOPER_GITLAB_URL:-https://gitlab.com}"
gitlab_token = "${ISTOTA_DEVELOPER_GITLAB_TOKEN:-}"
gitlab_username = "${ISTOTA_DEVELOPER_GITLAB_USERNAME:-}"
gitlab_default_namespace = "${ISTOTA_DEVELOPER_GITLAB_DEFAULT_NAMESPACE:-}"
gitlab_reviewer_id = "${ISTOTA_DEVELOPER_GITLAB_REVIEWER_ID:-}"
github_url = "${ISTOTA_DEVELOPER_GITHUB_URL:-https://github.com}"
github_token = "${ISTOTA_DEVELOPER_GITHUB_TOKEN:-}"
github_username = "${ISTOTA_DEVELOPER_GITHUB_USERNAME:-}"
github_default_owner = "${ISTOTA_DEVELOPER_GITHUB_DEFAULT_OWNER:-}"
github_reviewer = "${ISTOTA_DEVELOPER_GITHUB_REVIEWER:-}"
TOML
        if [ -n "${ISTOTA_DEVELOPER_AUTHOR_CREDIT:-}" ]; then
            echo "author_credit = \"${ISTOTA_DEVELOPER_AUTHOR_CREDIT}\"" >> "$CONFIG_FILE"
        fi
    fi

    # Briefing defaults (optional)
    if [ -n "${ISTOTA_BRIEFING_DEFAULTS_NEWS_LOOKBACK_HOURS:-}" ] || [ -n "${ISTOTA_BRIEFING_DEFAULTS_NEWS_SOURCES:-}" ]; then
        echo "" >> "$CONFIG_FILE"
        echo "[briefing_defaults]" >> "$CONFIG_FILE"
        echo "[briefing_defaults.news]" >> "$CONFIG_FILE"
        echo "lookback_hours = ${ISTOTA_BRIEFING_DEFAULTS_NEWS_LOOKBACK_HOURS:-12}" >> "$CONFIG_FILE"
    fi

    # Primary user
    cat >> "$CONFIG_FILE" <<TOML

[users.${USER_NAME}]
display_name = "${DISPLAY_NAME}"
timezone = "${TIMEZONE}"
TOML

    if [ -n "${USER_EMAIL:-}" ]; then
        echo "email_addresses = [\"${USER_EMAIL}\"]" >> "$CONFIG_FILE"
    fi
    if [ -n "${USER_LOG_CHANNEL:-}" ]; then
        echo "log_channel = \"${USER_LOG_CHANNEL}\"" >> "$CONFIG_FILE"
    fi
    if [ -n "${USER_NTFY_TOPIC:-}" ]; then
        echo "ntfy_topic = \"${USER_NTFY_TOPIC}\"" >> "$CONFIG_FILE"
    fi
    if [ -n "${USER_MAX_FOREGROUND_WORKERS:-}" ]; then
        echo "max_foreground_workers = ${USER_MAX_FOREGROUND_WORKERS}" >> "$CONFIG_FILE"
    fi
    if [ -n "${USER_MAX_BACKGROUND_WORKERS:-}" ]; then
        echo "max_background_workers = ${USER_MAX_BACKGROUND_WORKERS}" >> "$CONFIG_FILE"
    fi
    if [ -n "${USER_DISABLED_SKILLS:-}" ]; then
        echo "disabled_skills = [$(echo "$USER_DISABLED_SKILLS" | sed 's/[^,]*/"&"/g')]" >> "$CONFIG_FILE"
    fi

    echo "[istota] Config written to ${CONFIG_FILE}"
else
    echo "[istota] Config already exists, skipping generation."
fi

# --- Initialize database ---

echo "[istota] Initializing database..."
uv run istota -c "$CONFIG_FILE" init

# --- Claude Code authentication ---

echo "[istota] Configuring Claude Code..."
CLAUDE_DIR="${HOME}/.claude"
mkdir -p "$CLAUDE_DIR"

if [ -n "${CLAUDE_CODE_OAUTH_TOKEN:-}" ]; then
    # OAuth token provided — write credentials file
    echo "{\"claudeAiOauth\":{\"accessToken\":\"${CLAUDE_CODE_OAUTH_TOKEN}\",\"expiresAt\":\"9999-12-31T23:59:59.999Z\"}}" \
        > "$CLAUDE_DIR/.credentials.json"
    chmod 600 "$CLAUDE_DIR/.credentials.json"
    echo "[istota] Claude Code OAuth token configured."
elif [ -n "${ANTHROPIC_API_KEY:-}" ]; then
    echo "[istota] Using ANTHROPIC_API_KEY (direct API access)."
else
    echo "[istota] WARNING: No Claude Code credentials found. Set CLAUDE_CODE_OAUTH_TOKEN or ANTHROPIC_API_KEY."
fi

if claude --version >/dev/null 2>&1; then
    echo "[istota] Claude Code: $(claude --version 2>&1 | head -1)"
fi

# --- Start scheduler ---

echo "[istota] Starting scheduler daemon..."
exec uv run istota-scheduler --daemon -c "$CONFIG_FILE"
