#!/bin/bash
# Istota container entrypoint.
# Waits for Nextcloud provisioning, completes API-based setup, starts scheduler.

set -euo pipefail

CONFIG_FILE="/data/config/config.toml"
PROVISION_FLAG="/mnt/shared/.istota-provisioned"
API_PROVISION_FLAG="/data/config/.api-provisioned"
NC_URL="${NC_INTERNAL_URL:-http://nextcloud}"

# --- Wait for Nextcloud provisioning (occ-based, runs in NC container) ---

echo "[istota] Waiting for Nextcloud provisioning..."
WAIT=0
while [ ! -f "$PROVISION_FLAG" ]; do
    sleep 5
    WAIT=$((WAIT + 5))
    if [ "$WAIT" -ge 600 ]; then
        echo "[istota] ERROR: Timed out waiting for provisioning after 600s"
        exit 1
    fi
    if [ $((WAIT % 30)) -eq 0 ]; then
        echo "[istota] Still waiting for provisioning... (${WAIT}s)"
    fi
done

echo "[istota] Provisioning detected."

# shellcheck source=/dev/null
source "$PROVISION_FLAG"

# --- API-based provisioning (Talk room, uses NC HTTP API) ---

APP_PASSWORD="${BOT_PASSWORD}"
ROOM_TOKEN=""

if [ ! -f "$API_PROVISION_FLAG" ]; then
    echo "[istota] Running API-based provisioning..."

    # Wait for Nextcloud API to be responsive
    echo "[istota] Waiting for Nextcloud API..."
    for i in $(seq 1 30); do
        if curl -sf "${NC_URL}/status.php" | grep -q '"installed":true'; then
            echo "[istota] Nextcloud API ready."
            break
        fi
        sleep 2
    done

    # Create Talk 1:1 room
    ROOM_TOKEN=$(curl -sf \
        -u "${BOT_USER:-istota}:${BOT_PASSWORD}" \
        -H "OCS-APIRequest: true" \
        -H "Content-Type: application/json" \
        -X POST "${NC_URL}/ocs/v2.php/apps/spreed/api/v4/room?format=json" \
        -d "{\"roomType\":1,\"invite\":\"${USER_NAME}\"}" \
        | python3 -c "import sys,json; print(json.loads(sys.stdin.read())['ocs']['data']['token'])" 2>/dev/null || echo "")

    if [ -n "$ROOM_TOKEN" ]; then
        echo "[istota] Talk room created: ${ROOM_TOKEN}"
    else
        echo "[istota] Warning: could not create Talk room. Create one manually in Nextcloud Talk."
    fi

    # Save API provisioning results
    cat > "$API_PROVISION_FLAG" <<EOF
APP_PASSWORD=${APP_PASSWORD}
ROOM_TOKEN=${ROOM_TOKEN}
EOF

    echo "[istota] API provisioning complete."
else
    echo "[istota] API provisioning already done, reading results..."
    # shellcheck source=/dev/null
    source "$API_PROVISION_FLAG"
fi

# --- Generate config ---

if [ ! -f "$CONFIG_FILE" ]; then
    echo "[istota] Generating config.toml..."

    DISPLAY_NAME="${USER_DISPLAY_NAME:-$USER_NAME}"
    TIMEZONE="${USER_TIMEZONE:-UTC}"

    cat > "$CONFIG_FILE" <<TOML
# Istota configuration — generated by Docker entrypoint

bot_name = "Istota"

db_path = "/data/db/istota.db"
nextcloud_mount_path = "/mnt/shared"
skills_dir = "/app/config/skills"
temp_dir = "/data/tmp"

[security]
sandbox_enabled = false
skill_proxy_enabled = false

[security.network]
enabled = false

[nextcloud]
url = "${NC_URL}"
username = "${BOT_USER:-istota}"
app_password = "${APP_PASSWORD}"

[talk]
enabled = true
bot_username = "${BOT_USER:-istota}"

[email]
enabled = false

[conversation]
enabled = true
lookback_count = 25
skip_selection_threshold = 3
selection_model = "haiku"
use_selection = true
always_include_recent = 5

[logging]
level = "INFO"
output = "console"

[scheduler]
poll_interval = 5
talk_poll_interval = 10
talk_poll_timeout = 30
task_timeout_minutes = 30
max_foreground_workers = 3
max_background_workers = 2

[sleep_cycle]
enabled = true
cron = "0 2 * * *"
auto_load_dated_days = 3

[memory_search]
enabled = false

[users.${USER_NAME}]
display_name = "${DISPLAY_NAME}"
timezone = "${TIMEZONE}"
TOML

    echo "[istota] Config written to ${CONFIG_FILE}"
else
    echo "[istota] Config already exists, skipping generation."
fi

# --- Initialize database ---

echo "[istota] Initializing database..."
uv run istota -c "$CONFIG_FILE" init

# --- Claude Code authentication ---

echo "[istota] Configuring Claude Code..."
CLAUDE_DIR="${HOME}/.claude"
mkdir -p "$CLAUDE_DIR"

if [ -n "${CLAUDE_CODE_OAUTH_TOKEN:-}" ]; then
    # OAuth token provided — write credentials file
    echo "{\"claudeAiOauth\":{\"accessToken\":\"${CLAUDE_CODE_OAUTH_TOKEN}\",\"expiresAt\":\"9999-12-31T23:59:59.999Z\"}}" \
        > "$CLAUDE_DIR/.credentials.json"
    chmod 600 "$CLAUDE_DIR/.credentials.json"
    echo "[istota] Claude Code OAuth token configured."
elif [ -n "${ANTHROPIC_API_KEY:-}" ]; then
    echo "[istota] Using ANTHROPIC_API_KEY (direct API access)."
else
    echo "[istota] WARNING: No Claude Code credentials found. Set CLAUDE_CODE_OAUTH_TOKEN or ANTHROPIC_API_KEY."
fi

if claude --version >/dev/null 2>&1; then
    echo "[istota] Claude Code: $(claude --version 2>&1 | head -1)"
fi

# --- Start scheduler ---

echo "[istota] Starting scheduler daemon..."
exec uv run istota-scheduler --daemon -c "$CONFIG_FILE"
