import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Explicit, not autogenerated: the order here is the curated order `mkdocs.yml`
// carried, and an autogenerated sidebar would sort these alphabetically and
// lose it. A new page has to be listed, which is the intended cost.
const sidebars: SidebarsConfig = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: [
        'getting-started/quickstart-docker',
        'getting-started/quickstart-bare-metal',
        'getting-started/local-install',
        'getting-started/post-install',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/overview',
        'architecture/task-lifecycle',
        'architecture/scheduler',
        'architecture/executor',
        'architecture/brain',
        'architecture/context',
        'architecture/memory',
        'architecture/database',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      items: [
        'features/skills',
        'features/memory',
        'features/briefings',
        'features/scheduling',
        'features/heartbeat',
        'features/feeds',
        'features/money',
        'features/location',
        'features/health',
        'features/nextcloud',
        'features/google-workspace',
        'features/web-interface',
        'features/notifications',
        'features/usage',
      ],
    },
    {
      // The conversation surfaces — the ones a person sends to and gets a
      // reply from, each sitting behind the same Transport seam. Deliberately
      // not everything that can reach a user: `features/notifications` is the
      // web UI's inbox and `features/usage` is reporting, and neither is a
      // surface you hold a conversation on.
      //
      // The files stay under `docs/features/`, so these pages keep their URLs.
      // Their paths are named from the Ansible defaults, the compose comments,
      // `.claude/rules/` and several docstrings; moving them is a much larger
      // change than regrouping the nav, and is not what this is.
      type: 'category',
      label: 'Messaging',
      link: {
        type: 'generated-index',
        title: 'Messaging surfaces',
        description:
          'The surfaces a person talks to Istota through. Each is reached by the same task pipeline, and which ones a deployment runs is a configuration choice.',
        slug: '/messaging',
      },
      items: [
        'features/web-chat',
        'features/talk',
        'features/email',
        'features/whatsapp',
        'features/sms',
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      items: [
        'configuration/overview',
        'configuration/reference',
        'configuration/per-user',
        'configuration/credentials',
        'configuration/persona',
        'configuration/native-brain',
        'EXPERIMENTAL',
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        'deployment/ansible',
        'deployment/docker',
        'deployment/security',
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        'development/setup',
        'development/testing',
        'development/adding-skills',
        'development/secret-scanning',
        'development/development-rules-user',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/cli',
        'reference/commands',
        'reference/skills-index',
        'reference/environment-variables',
      ],
    },
  ],
};

export default sidebars;
