"""The stack's devbox services, rendered from the config.

Compose cannot loop over users, so ``istota devbox compose-file`` renders a
second compose file, ``compose.devbox.yml``, which ``istota-stack`` passes as a
second ``-f`` beside ``docker/docker-compose.yml``. One ``devbox-<user>``
service per ``[devbox] users`` entry, carrying what the Ansible role's
``docker-compose.devbox.yml.j2`` renders today: the build at uid and gid 10001,
the ownership label, the limits, the network, the supervisor as the command and
its environment, and the mounts.

The mounts are where this differs from the role, and they are the boundary:

- ``devbox-exec-<user>`` and ``devbox-cred-<user>`` are named volumes. The
  istota container mounts every user's pair, at ``{exec_socket_dir}/<user>`` and
  ``{devbox_proxy_socket_dir}/<user>`` (it serves them all); each devbox mounts
  only its own, at ``/run/istota-exec`` and ``/run/istota-cred``. Only U's devbox
  can reach U's credential socket, which is how the proxy knows who a client is
  (``devbox/proxy.py``).
- The repos are the user's own subdirectory of the istota state volume, mounted
  at the same absolute path on both sides, so a working directory needs no
  translation.

Both socket directories and the repos root must be under ``/data``: the istota
container's root phase hands writable mounts under ``/data`` to the daemon's
uid on every start, and a fresh volume is root-owned. A config placing one
anywhere else is refused rather than rendered into a stack whose daemon cannot
bind its sockets.

The output is JSON, which YAML reads as it is, under a comment header. The
runtime has no YAML library, and ``json.dumps`` quotes every string correctly
without a hand-written escaper.
"""

from __future__ import annotations

import json
import re
from pathlib import PurePosixPath

from istota.maintenance.sandbox_cache_sweeper import CACHE_NPM, CACHE_ROOT_NAME, CACHE_UV

#: uid and gid of the daemon and of `dev` in the devbox image, by construction.
ISTOTA_UID = 10001

#: The istota container's state volume, as `docker/docker-compose.yml` names it.
STATE_VOLUME = "istota_data"
STATE_MOUNT = PurePosixPath("/data")

#: Where a devbox sees its own two socket directories. `/run/istota-cred/sock`
#: is baked into the image (`ISTOTA_CRED_SOCK`); the exec server refuses both
#: directories by name as file roots.
DEVBOX_EXEC_DIR = "/run/istota-exec"
DEVBOX_CRED_DIR = "/run/istota-cred"
DEVBOX_HOME = "/home/dev"
DEVBOX_SUPERVISOR = "/usr/local/bin/istota-exec-run"

#: The build context, relative to the first compose file's directory, which is
#: what compose resolves every `-f` file's paths against.
BUILD_CONTEXT = "devbox"

NETWORK = "devbox"

# A compose service and volume name allows these, and a user id is a component
# of both. Anything else is refused rather than mangled into someone else's name.
_USER_ID = re.compile(r"^[a-zA-Z0-9][a-zA-Z0-9_.-]*$")

HEADER = (
    "# Generated by `istota devbox compose-file` from [devbox] in config.toml.\n"
    "# Do not edit: istota-stack rewrites it. One devbox service per user, and\n"
    "# the istota service's mounts of every user's two socket volumes.\n"
)


class ComposeFileError(ValueError):
    """The config cannot be rendered into a working devbox stack."""


def _under_state(path: str, what: str) -> PurePosixPath:
    p = PurePosixPath(path)
    if not p.is_absolute() or ".." in p.parts:
        raise ComposeFileError(f"{what} {path!r} is not an absolute path")
    try:
        p.relative_to(STATE_MOUNT)
    except ValueError:
        raise ComposeFileError(
            f"{what} is {path!r}, which is not under {STATE_MOUNT}. The istota "
            f"container's root phase hands only mounts under {STATE_MOUNT} to "
            f"uid {ISTOTA_UID}, so a socket volume anywhere else stays root-owned "
            f"and nothing can bind in it."
        ) from None
    if p == STATE_MOUNT:
        raise ComposeFileError(f"{what} cannot be {STATE_MOUNT} itself")
    return p


def devbox_users(config) -> list[str]:
    """The users to render a devbox for, validated and in config order."""
    devbox = getattr(config, "devbox", None)
    if not getattr(devbox, "enabled", False):
        return []
    users: list[str] = []
    for user in getattr(devbox, "users", None) or []:
        if not isinstance(user, str) or not _USER_ID.match(user):
            raise ComposeFileError(
                f"[devbox] users entry {user!r} is not a usable user id "
                "(letters, digits, '.', '_' and '-', not starting with a symbol)"
            )
        if user in users:
            raise ComposeFileError(f"[devbox] users names {user!r} twice")
        users.append(user)
    return users


def _volume(source: str, target: str, **extra) -> dict:
    entry = {"type": "volume", "source": source, "target": target}
    entry.update(extra)
    return entry


def build_document(config) -> dict:
    """The compose document as a dict. Raises `ComposeFileError`."""
    from istota.config import devbox_container_backend

    users = devbox_users(config)
    if not users:
        return {"services": {}}

    dev = config.developer
    devbox = config.devbox
    exec_root = _under_state(dev.container.exec_socket_dir, "[developer.container] exec_socket_dir")
    proxy_on = bool(getattr(dev, "devbox_proxy_enabled", True))
    cred_root = (
        _under_state(dev.devbox_proxy_socket_dir, "[developer] devbox_proxy_socket_dir")
        if proxy_on else None
    )
    transport = devbox_container_backend(config)
    repos_root = (
        _under_state(dev.repos_dir.strip().rstrip("/"), "[developer] repos_dir")
        if transport else None
    )
    if cred_root is not None and (exec_root == cred_root):
        raise ComposeFileError(
            "the exec and credential socket directories are the same; each user's "
            "two volumes would be mounted on one path"
        )

    services: dict = {}
    volumes: dict = {}
    istota_mounts: list[dict] = []

    for user in users:
        name = f"{devbox.container_prefix}{user}"
        exec_volume = f"devbox-exec-{user}"
        cred_volume = f"devbox-cred-{user}"
        home_volume = f"devbox-home-{user}"
        volumes[home_volume] = {}
        volumes[exec_volume] = {}

        mounts = [
            _volume(home_volume, DEVBOX_HOME),
            _volume(exec_volume, DEVBOX_EXEC_DIR),
        ]
        istota_mounts.append(_volume(exec_volume, str(exec_root / user)))
        if cred_root is not None:
            volumes[cred_volume] = {}
            mounts.append(_volume(cred_volume, DEVBOX_CRED_DIR))
            istota_mounts.append(_volume(cred_volume, str(cred_root / user)))

        service: dict = {
            "build": {
                "context": BUILD_CONTEXT,
                "dockerfile": "Dockerfile",
                "args": {"DEV_UID": str(ISTOTA_UID), "DEV_GID": str(ISTOTA_UID)},
            },
            "image": "istota-devbox:${ISTOTA_TAG:-local}",
            "hostname": name,
            "restart": "unless-stopped",
            "labels": {"com.istota.user_id": user},
            # The root phase hands the socket volumes to uid 10001 before the
            # istota healthcheck can pass, so the server here can bind in them.
            "depends_on": {"istota": {"condition": "service_healthy"}},
            "networks": [NETWORK],
            "mem_limit": devbox.mem_limit,
            "cpus": devbox.cpus,
            "pids_limit": devbox.pids_limit,
            # tini at PID 1 reaps what reparents to it; the supervisor never
            # waits on a process it did not start.
            "init": True,
            "logging": {
                "driver": "json-file",
                "options": {
                    "max-size": devbox.log_max_size,
                    "max-file": str(devbox.log_max_file),
                },
            },
            "command": [DEVBOX_SUPERVISOR],
            "volumes": mounts,
        }
        if repos_root is not None:
            user_repos = repos_root / user
            mounts.append(_volume(
                STATE_VOLUME, str(user_repos),
                volume={"subpath": str(user_repos.relative_to(STATE_MOUNT))},
            ))
            caches = user_repos / CACHE_ROOT_NAME
            service["environment"] = {
                "ISTOTA_EXEC_SOCKET": f"{DEVBOX_EXEC_DIR}/exec.sock",
                "ISTOTA_EXEC_REPOS_ROOT": str(user_repos),
                "ISTOTA_EXEC_IDLE_TIMEOUT_SECONDS": str(dev.container.idle_timeout_seconds),
                "CARGO_HOME": f"{DEVBOX_HOME}/.cargo",
                "GOMODCACHE": f"{DEVBOX_HOME}/go/pkg/mod",
                "UV_PYTHON_INSTALL_DIR": f"{DEVBOX_HOME}/.uv-python",
                # The same subdirectories the host writes and the sweeper
                # reclaims, or every wheel is kept twice.
                "UV_CACHE_DIR": str(caches / CACHE_UV),
                "npm_config_cache": str(caches / CACHE_NPM),
            }
        services[name] = service

    services["istota"] = {"volumes": istota_mounts}
    return {
        "services": services,
        "volumes": volumes,
        "networks": {
            NETWORK: {
                "driver": "bridge",
                "ipam": {"config": [{"subnet": devbox.network_subnet}]},
            },
        },
    }


def render_devbox_compose(config) -> str:
    """The text of `compose.devbox.yml`. Raises `ComposeFileError`."""
    return HEADER + json.dumps(build_document(config), indent=2) + "\n"


def repos_dirs_to_create(config) -> list[str]:
    """Each user's repos directory, which a `subpath` mount needs to exist."""
    from istota.config import devbox_container_backend

    if not devbox_container_backend(config):
        return []
    root = _under_state(config.developer.repos_dir.strip().rstrip("/"), "[developer] repos_dir")
    return [str(root / user) for user in devbox_users(config)]
