/**
 * Stub for SvelteKit's `$app/navigation` under vitest.
 *
 * The real module is generated by `svelte-kit sync` and only resolvable inside
 * a Kit build. Component tests that mount anything reaching the `ui` barrel
 * (which pulls in HeaderNav) need it to resolve; nothing under test navigates.
 */
export function goto(_url: string): Promise<void> {
  return Promise.resolve();
}

export function invalidateAll(): Promise<void> {
  return Promise.resolve();
}

export function afterNavigate(_callback: () => void): void {
  // Nothing under test navigates; the callback simply never fires.
}
