import { resolve } from 'node:path';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import { defineConfig } from 'vitest/config';

// Component tests (`*.svelte.test.ts`) mount real Svelte components under jsdom
// to verify rendering + reactivity; the pure reducer tests (`segments.test.ts`)
// need no DOM but run fine here too. The Svelte plugin compiles components.
export default defineConfig({
  plugins: [svelte({ hot: false })],
  // The two build stamps `vite.config.ts` substitutes. They are bare
  // identifiers in the source, so a component that logs one — the root layout
  // does, on its first line — dies with a `ReferenceError` under a config that
  // does not define them, before any of its own code runs.
  define: {
    __APP_VERSION__: JSON.stringify('0.0.0-test'),
    __APP_BUILT_AT__: JSON.stringify('1970-01-01T00:00:00Z'),
  },
  resolve: {
    alias: {
      $lib: resolve(__dirname, 'src/lib'),
      // `$app/*` is generated by `svelte-kit sync` and only resolvable inside
      // a Kit build. Stub it so component tests can mount anything importing
      // the `ui` barrel (HeaderNav pulls in `$app/navigation`).
      '$app/navigation': resolve(__dirname, 'vitest-stubs/app-navigation.ts'),
      '$app/paths': resolve(__dirname, 'vitest-stubs/app-paths.ts'),
      '$app/state': resolve(__dirname, 'vitest-stubs/app-state.ts'),
      // Same reasoning for `$service-worker`, which Kit generates per build
      // and resolves only inside the worker bundle.
      '$service-worker': resolve(__dirname, 'vitest-stubs/service-worker.ts'),
    },
    // Use the browser entry for Svelte so runtime imports resolve under vitest.
    conditions: ['browser'],
  },
  test: {
    // scripts/ holds the design-lint rule tests: the lint's failure mode is a
    // regex that quietly stops matching, so the rules need coverage like any
    // other logic.
    include: ['src/**/*.test.ts', 'scripts/**/*.test.ts'],
    environment: 'jsdom',
    setupFiles: ['./vitest-setup.ts'],
  },
});
